# importing the module 
import pandas as pd 
import csv

# making data frame from the csv file 
dataframe = pd.read_csv("/home/youffes/finaly/table.csv") 
	
# using the replace() method 
dataframe.replace(to_replace ="433", 
				value = "h.hamdi", 
				inplace = True)
dataframe.replace(to_replace ="433.0", 
				value = "h.hamdi", 
				inplace = True)
dataframe.replace(to_replace ="404", 
				value = "MohamedAli.HABAYEB", 
				inplace = True)
dataframe.replace(to_replace ="671", 
				value = "i.benyahya", 
				inplace = True)
dataframe.replace(to_replace ="408", 
				value = "Recouvrement", 
				inplace = True)
dataframe.replace(to_replace ="408.0", 
				value = "Recouvrement", 
				inplace = True)
dataframe.replace(to_replace ="473", 
				value = "i.zammit", 
				inplace = True)
dataframe.replace(to_replace ="437", 
				value = "a.belhajalaya", 
				inplace = True)
dataframe.replace(to_replace ="416", 
				value = "k.haouala", 
				inplace = True)
dataframe.replace(to_replace ="420", 
				value = "a.loukil", 
				inplace = True)
dataframe.replace(to_replace ="454", 
				value = "b.benammar", 
				inplace = True)
dataframe.replace(to_replace ="471", 
				value = "J.Bedoui", 
				inplace = True)
dataframe.replace(to_replace ="471.0", 
				value = "J.Bedoui", 
				inplace = True)
dataframe.replace(to_replace ="479", 
				value = "m.hajri", 
				inplace = True)
dataframe.replace(to_replace ="423", 
				value = "s.ettaieb", 
				inplace = True)
dataframe.replace(to_replace ="493", 
				value = "m.daassi", 
				inplace = True)
dataframe.replace(to_replace ="493.0", 
				value = "m.daassi", 
				inplace = True)
dataframe.replace(to_replace ="660", 
				value = "s.missaoui", 
				inplace = True)
dataframe.replace(to_replace ="123", 
				value = "m.hammami", 
				inplace = True)
dataframe.replace(to_replace ="458", 
				value = "f.siala", 
				inplace = True)
dataframe.replace(to_replace ="411", 
				value = "a.arfaoui", 
				inplace = True)
dataframe.replace(to_replace ="411.0", 
				value = "a.arfaoui", 
				inplace = True)
dataframe.replace(to_replace ="434", 
				value = "s.mnaja", 
				inplace = True)
dataframe.replace(to_replace ="410", 
				value = "H.DJEGHOUBI,", 
				inplace = True)
dataframe.replace(to_replace ="410.0", 
				value = "H.DJEGHOUBI,", 
				inplace = True)
dataframe.replace(to_replace ="422", 
				value = "a.ghorbel", 
				inplace = True)
dataframe.replace(to_replace ="422.0", 
				value = "a.ghorbel", 
				inplace = True)
dataframe.replace(to_replace ="408", 
				value = "w.mahmoudi", 
				inplace = True)
dataframe.replace(to_replace ="480", 
				value = "m.kbaier", 
				inplace = True)
dataframe.replace(to_replace ="481", 
				value = "m.yahyaoui", 
				inplace = True)
dataframe.replace(to_replace ="464", 
				value = "o.benrhouma", 
				inplace = True)
dataframe.replace(to_replace ="460", 
				value = "i.gatfi", 
				inplace = True)
dataframe.replace(to_replace ="431", 
				value = "m.jendoubi", 
				inplace = True)	
dataframe.replace(to_replace ="485", 
				value = "R.CHEBBI", 
				inplace = True)	
dataframe.replace(to_replace ="422", 
				value = "a.ghorbel", 
				inplace = True)
dataframe.replace(to_replace ="422.0", 
				value = "a.ghorbel", 
				inplace = True)
dataframe.replace(to_replace ="661", 
				value = "s.marzouki", 
				inplace = True)
dataframe.replace(to_replace ="457", 
				value = "c.setti", 
				inplace = True)
dataframe.replace(to_replace ="456", 
				value = "c.allouche", 
				inplace = True)
dataframe.replace(to_replace ="476", 
				value = "ab.belhaj", 
				inplace = True)
dataframe.replace(to_replace ="462", 
				value = "k.bouchriha", 
				inplace = True)
dataframe.replace(to_replace ="451", 
				value = "M.KACHOUKH", 
				inplace = True) 
dataframe.replace(to_replace ="468", 
				value = "t.jendoubi", 
				inplace = True)
dataframe.replace(to_replace ="482", 
				value = "m.toukebri", 
				inplace = True)
dataframe.replace(to_replace ="635", 
				value = "guest", 
				inplace = True)
dataframe.replace(to_replace ="401", 
				value = "k.abdeljaoued", 
				inplace = True)
dataframe.replace(to_replace ="401.0", 
				value = "k.abdeljaoued", 
				inplace = True)
dataframe.replace(to_replace ="402", 
				value = "k.bousnina", 
				inplace = True)
dataframe.replace(to_replace ="402.0", 
				value = "k.bousnina", 
				inplace = True)
dataframe.replace(to_replace ="407", 
				value = "omar.darragi", 
				inplace = True)
dataframe.replace(to_replace ="483", 
				value = "w.meddeb", 
				inplace = True)	
dataframe.replace(to_replace ="412", 
				value = "r.bahloul", 
				inplace = True)
dataframe.replace(to_replace ="304", 
				value = "intrinsec", 
				inplace = True)
dataframe.replace(to_replace ="444", 
				value = "DaVinci", 
				inplace = True)
dataframe.replace(to_replace ="633", 
				value = "VisioOTH", 
				inplace = True)
dataframe.replace(to_replace ="488", 
				value = "w.edhkar", 
				inplace = True)
dataframe.replace(to_replace ="426", 
				value = "amel.belanteur", 
				inplace = True)
dataframe.replace(to_replace ="340", 
				value = "Moncef.Sellami", 
				inplace = True)
dataframe.replace(to_replace ="341", 
				value = "Sonia.Chaieb", 
				inplace = True)
dataframe.replace(to_replace ="413", 
				value = "a.baccouche", 
				inplace = True)
dataframe.replace(to_replace ="413.0", 
				value = "a.baccouche", 
				inplace = True)
dataframe.replace(to_replace ="400", 
				value = "i.blanco", 
				inplace = True)
dataframe.replace(to_replace ="407", 
				value = "Leila.Affes", 
				inplace = True)
dataframe.replace(to_replace ="327", 
				value = "a.chkondali", 
				inplace = True)
				

# writing the dataframe to another csv file 
dataframe.to_csv('/home/youffes/finaly/outputfile.csv', 
				index = False)
